---
- name: KDE
  hosts: 
    - localhost
  roles:
  tasks:
  - name: Install kde packages
    ansible.builtin.package:
      name:
        - libpam-kwallet5
        - plasma-workspace-wallpapers
      state: latest
    become: true
    tags: packages
