---
- name: Tumbleweed packages
  hosts: 
    - localhost
  roles:
  tasks:
  - name: Install tumbleweed packages
    ansible.builtin.package:
      name:
        - wget
        - direnv
        - fzf
        - rcm
        - vim
        - curl
      state: latest
    become: true
    tags: packages
